# This file contains all available configuration options
# with their default values (in comments).
#
# This file is not a configuration example,
# it contains the exhaustive configuration with explanations of the options.

# Defines the configuration version.
# The only possible value is "2".
version: "2"
#
linters:
# Default set of linters.
# The value can be:
# - `standard`: https://golangci-lint.run/docs/linters/#enabled-by-default
# - `all`: enables all linters by default.
# - `none`: disables all linters by default.
# - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq '[ .[] | select(.fast==true) ] | map(.name)'`).
# Default: standard
  default: standard

  # Enable a balanced set of linters for a Kubernetes operator
  enable:
    # Default linters
    - errcheck # Check for unchecked errors
    - govet # Suspicious constructs
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Advanced static analysis
    - unused # Checks for unused code

    # Additional linters for code quality
    - bodyclose # Checks that HTTP response bodies are closed
    - dupl # Detect code clones
    - durationcheck # Check for two durations multiplied together
    - errorlint # Checks for error handling issues
    - funlen # Check function length
    - gocognit # Calculate cognitive complexity
    - goconst # Find repeated strings that could be constants
    - gocritic # Provides many diagnostics
    - gocyclo # Check cyclomatic complexity
    - misspell # Find misspelled words
    - prealloc # Find slice declarations that could be prealloc'd
    - revive # Fast, configurable, linter
    - unconvert # Remove unnecessary type conversions
    - unparam # Find unused function parameters

  settings:
    gocyclo:
      min-complexity: 15
    funlen:
      lines: 100
      statements: 50
    revive:
      rules:
        - name: comment-spacings
    gocritic:
      enabled-checks:
        # Only keep the checks that aren't enabled by default
        - commentedOutCode
        - commentedOutImport
        - nilValReturn
        - sloppyReassign
        - weakCond
        - rangeValCopy
        - hugeParam

  exclusions:
    # Mode of the generated files analysis.
    #
    # - `strict`: sources are excluded by strictly following the Go generated file convention.
    #    Source files that have lines matching only the following regular expression will be excluded: `^// Code generated .* DO NOT EDIT\.$`
    #    This line must appear before the first non-comment, non-blank text in the file.
    #    https://go.dev/s/generatedcode
    # - `lax`: sources are excluded if they contain lines like `autogenerated file`, `code generated`, `do not edit`, etc.
    # - `disable`: disable the generated files exclusion.
    #
    # Default: strict
    generated: lax
    # Log a warning if an exclusion rule is unused.
    # Default: false
    warn-unused: true
    # Predefined exclusion rules.
    # Default: []
    rules:
      # Exclude some linters from running on test files.
      - path: _test\.go
        linters:
          - dupl


# Options for analysis running.
run:
# Timeout for total work, e.g. 30s, 5m, 5m30s.
# If the value is lower or equal to 0, the timeout is disabled.
# Default: 0 (disabled)
  timeout: 5m
# The mode used to evaluate relative paths.
# It's used by exclusions, Go plugins, and some linters.
# The value can be:
# - `gomod`: the paths will be relative to the directory of the `go.mod` file.
# - `gitroot`: the paths will be relative to the git root (the parent directory of `.git`).
# - `cfg`: the paths will be relative to the configuration file.
# - `wd` (NOT recommended): the paths will be relative to the place where golangci-lint is run.
# Default: cfg
  relative-path-mode: gomod
# Allow multiple parallel golangci-lint instances running.
# If false, golangci-lint acquires file lock on start.
# Default: false
  allow-parallel-runners: true

issues:
  exclude-use-default: false
