ARG DOCKER_MIRROR=docker.io/

FROM ${DOCKER_MIRROR}golang:alpine AS builder

WORKDIR /app

COPY . .

RUN go get ./...
RUN CGO_ENABLED=0 go build -o switchboard -ldflags '-w -extldflags "-static"' cmd/switchboard/main.go

FROM ${DOCKER_MIRROR}golang:alpine

RUN apk update && apk add bash && apk add busybox-extras

WORKDIR /
COPY --from=builder /app/switchboard /bin/switchboard

ENTRYPOINT ["/bin/switchboard"]
