apiVersion: ror.nhn.no/v1alpha1
kind: Task
metadata:
    labels:
        app.kubernetes.io/name: task
        app.kubernetes.io/instance: task-sample
        app.kubernetes.io/part-of: operator
        app.kuberentes.io/managed-by: kustomize
        app.kubernetes.io/created-by: operator
    name: test-task

spec:
    backoffLimit: 1
    imagePostfix: jobbase
    envVars:
        - key: test
          value: tester
    timeoutInSeconds: 60
    cmd: 'test'
    gitConfig:
        token: 'test'
        user: 'test'
        repository: 'test'
version: 0.0.1
index: 1
runOnce: true
