kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rms-slack.fullname" . }}-rolebindings
roleRef:
  kind: ClusterRole
  name: psp:vmware-system-restricted #Kan erstattes med: "psp:vmware-system-privileged" for root access
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "ms-slack.serviceAccountName" . }}
