apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ms-switchboard.fullname" . }}
  labels:
    {{- include "ms-switchboard.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ default "INFO" .Values.switchboard.logLevel | quote }}
  ENVIRONMENT: {{ default "Production" .Values.switchboard.environment | quote }}
  RABBITMQ_HOST: {{ default "rabbitmq-ror.nhn-ror.svc" .Values.switchboard.rabbitmqHost | quote }}
  RABBITMQ_PORT: {{ default "5672" .Values.switchboard.rabbitmqPort | quote }}
  OPENTELEMETRY_COLLECTOR_ENDPOINT: {{ default "ror-opentelemetry-collector.nhn-ror.svc:4317" .Values.switchboard.otelCollectorEndpoint | quote}}
  VAULT_URL: {{ default "http://ror-vault-active.nhn-ror.svc:8200" .Values.switchboard.vaultUrl | quote }}
  VAULT_TOKEN_TTL: {{ default "24h" .Values.switchboard.vaultTokenTtl | quote }}
  VAULT_TOKEN_K8S_PATH: {{ default "/var/run/secrets/kubernetes.io/serviceaccount/token" .Values.switchboard.vaultTokenK8sPath | quote }}
  ROLE: {{ default "ror-ms-switchboard" .Values.switchboard.role | quote }}
