
ARG DOCKER_MIRROR=docker.io/
FROM ${DOCKER_MIRROR}golang:alpine AS builder
RUN mkdir -p /api
WORKDIR /app
COPY . .

RUN go get ./...
RUN CGO_ENABLED=0 go build -o ror-api -ldflags '-w -extldflags "-static"' cmd/api/main.go

FROM ${DOCKER_MIRROR}golang:alpine
RUN apk update && apk add bash && apk add busybox-extras

WORKDIR /
COPY --from=builder /app/ror-api /bin/ror-api

ENTRYPOINT ["/bin/ror-api"]
