apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-{{ .Release.Name}}-docs
  namespace: {{ .Release.namespace}}
spec:
  policyTypes:
  - Egress
  - Ingress
  podSelector:
    matchLabels: 
      run: {{ .Release.Name}}-docs
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: UDP
      port: 1053
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 169.254.169.254/32
          - 193.0.2.0/16
          - 195.51.100.0/12
          - 10.204.0.0/23
          - 10.204.2.0/23
          - 10.204.4.0/23
          - 10.204.6.0/23
  ingress:
  - ports:
    - port: 8080