apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-docs-publisering
  namespace: {{ .Release.namespace}}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "ror-dokumentasjon"
  type: NodePort