ARG DOCKER_MIRROR=docker.io/
ARG GCR_MIRROR=gcr.io/
FROM ${DOCKER_MIRROR}golang1.23-alpine as builder
WORKDIR /app
COPY . .
RUN go get ./...

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o dist/ror-agent cmd/agent/main.go

FROM ${GCR_MIRROR}distroless/static:nonroot
WORKDIR /
COPY --from=builder /app/dist/ror-agent .
USER 10000:10000

ENTRYPOINT ["/ror-agent"]
