apiVersion: v1
kind: Service
metadata:
  name: {{ include "ms-tanzu-auth.fullname" . }}
  labels:
    {{- include "ms-tanzu-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "ms-tanzu-auth.selectorLabels" . | nindent 4 }}
