{{- range .Values.agents }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ror-tanzu-agent:psp
  namespace: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:vmware-system-restricted
subjects:
- kind: ServiceAccount
  name: ror-tanzu-agent-sa
  namespace: {{ .name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ror-tanzu-agent:rolebinding
  namespace: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ror-tanzu-agent:role
subjects:
- kind: ServiceAccount
  name: ror-tanzu-agent-sa
  namespace: {{ .name }}
{{- end }}