services:
  api:
    restart: always
    platform: linux/amd64
    ports:
      - '10000:8080'
    depends_on:
      dex:
        condition: service_started
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      vault:
        condition: service_healthy
    links:
      - dex
      - mongodb
      - rabbitmq
      - vault
    environment:
      - USE_CORS=true
      - LOG_LEVEL=debug
      - GIN_MODE=debug
      - ALLOW_ORIGINS=https://ror.sky.test.nhn.no;http://localhost:11000;http://127.0.0.1:11000
      - HTTP_PORT=10000
      - VAULT_URL=http://vault:8200
      - MONGODB_PORT=27017
      - OPENTELEMETRY_COLLECTOR_ENDPOINT=opentelemetry-collector:4317
      - DEVELOPMENT=false
      - LOCALHOST=false
      - ENABLE_TRACING=false
      - PROFILER_ENABLED=false
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
      - HEALTHCHECK_ENDPOINT=localhost:9999
    volumes:
      - ../data/secrets:/tmp/secrets:rw
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://api:8080']
      interval: 30s
      timeout: 10s
      retries: 5
