services:
  ms-nhn:
    image: ${ROR_REPO}ms-nhn:${ROR_BUILD_TAG}

  ms-auth:
    image: ${ROR_REPO}ms-auth:${ROR_BUILD_TAG}

  ms-slack:
    image: ${ROR_REPO}ms-slack:${ROR_BUILD_TAG}

  ms-switchboard:
    image: ${ROR_REPO}ms-switchboard:${ROR_BUILD_TAG}

  ms-audit:
    image: ${ROR_REPO}ms-audit:${ROR_BUILD_TAG}

  ms-kind:
    image: ${ROR_REPO}ms-kind:${ROR_BUILD_TAG}

  ms-talos:
    image: ${ROR_REPO}ms-talos:${ROR_BUILD_TAG}
