services:
  ms-nhn:
    image: ${ROR_REPO}ror-ms-nhn:${ROR_BUILD_TAG}

  ms-auth:
    image: ${ROR_REPO}ror-ms-auth:${ROR_BUILD_TAG}

  ms-slack:
    image: ${ROR_REPO}ror-ms-slack:${ROR_BUILD_TAG}

  ms-switchboard:
    image: ${ROR_REPO}ror-ms-switchboard:${ROR_BUILD_TAG}

  ms-audit:
    image: ${ROR_REPO}ror-ms-audit:${ROR_BUILD_TAG}

  ms-kind:
    image: ${ROR_REPO}ror-ms-kind:${ROR_BUILD_TAG}

  ms-talos:
    image: ${ROR_REPO}ror-ms-talos:${ROR_BUILD_TAG}
