services:
  ms-nhn:
    build:
      context: ../../
      dockerfile: cmd/nhn/Dockerfile.compose

  ms-auth:
    build:
      context: ../../
      dockerfile: cmd/auth/Dockerfile.compose

  ms-slack:
    build:
      context: ../../
      dockerfile: cmd/slack/Dockerfile.compose

  ms-switchboard:
    build:
      context: ../../
      dockerfile: cmd/switchboard/Dockerfile.compose

  ms-audit:
    build:
      context: ../../
      dockerfile: cmd/audit/Dockerfile.compose

  ms-kind:
    build:
      context: ../../
      dockerfile: cmd/kind/Dockerfile.compose

  ms-talos:
    build:
      context: ../../
      dockerfile: cmd/talos/Dockerfile.compose
