services:
  web:
    image: ghcr.io/norskhelsenett/ror-webapp:latest
    ports:
      - "11000:11000"
    platform: linux/amd64
    volumes:
      - type: bind
        source: ../data/web/config.json
        target: /app/assets/config/config.json
      - type: bind
        source: ../data/web/admin/nginx/http_compose.conf
        target: /etc/nginx/conf.d/default.conf

