services:
  web:
    build:
      context: ../../web/admin/
      dockerfile: Dockerfile.compose
      args:
        DEX_PORT: 5556
        API_PORT: 10000
    ports:
      - "11000:8090"
    volumes:
      - type: bind
        source: ../../web/admin/nginx/http_compose.conf
        target: /etc/nginx/conf.d/default.conf
