
ARG DOCKER_MIRROR=docker.io/

FROM ${DOCKER_MIRROR}golang:alpine AS builder

RUN mkdir -p /api
WORKDIR /app

COPY . .

RUN go get ./...
RUN CGO_ENABLED=0 go build -o nhn -ldflags '-w -extldflags "-static"' cmd/nhn/main.go

FROM ${DOCKER_MIRROR}golang:alpine

RUN apk update && apk add bash && apk add busybox-extras

WORKDIR /
COPY --from=builder /app/nhn /bin/nhn

ENTRYPOINT ["/bin/nhn"]
