apiVersion: ror.nhn.no/v1alpha1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: task
    app.kubernetes.io/instance: task-sample
    app.kubernetes.io/part-of: ROR Operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ROR Operator
  name: task-sample
spec:
  # TODO(user): Add fields here
