package apiresourcecontracts

// K8s PolicyReport struct generated by kyverno// Deprecated: This type is only to be used in resource/v1 and will be deprecated
type ResourcePolicyReport struct {
	ApiVersion   string                        `json:"apiVersion"`
	Kind         string                        `json:"kind"`
	Metadata     ResourceMetadata              `json:"metadata"`
	Results      []ResourcePolicyReportResults `json:"results"`
	Summary      ResourcePolicyReportSummary   `json:"summary"`
	LastReported string                        `json:"lastReported,omitempty"`
}

// Deprecated: This type is only to be used in resource/v1 and will be deprecated
type ResourcePolicyReportResults struct {
	Policy     string                                 `json:"policy"`
	Message    string                                 `json:"message"`
	Category   string                                 `json:"category"`
	Properties map[string]string                      `json:"properties"`
	Severity   string                                 `json:"severity"`
	Result     string                                 `json:"result"`
	Resources  []ResourcePolicyReportResultsResources `json:"resources"`
}

// Deprecated: This type is only to be used in resource/v1 and will be deprecated
type ResourcePolicyReportResultsResources struct {
	Uid        string `json:"uid"`
	ApiVersion string `json:"apiVersion"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
}

// Deprecated: This type is only to be used in resource/v1 and will be deprecated
type ResourcePolicyReportSummary struct {
	Error int `json:"error"`
	Fail  int `json:"fail"`
	Pass  int `json:"pass"`
	Skip  int `json:"skip"`
	Warn  int `json:"warn"`
}
