apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ms-slack.fullname" . }}
  labels:
    {{- include "ms-slack.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ default "INFO" .Values.slack.logLevel | quote }}
  ENVIRONMENT: {{ default "Production" .Values.slack.environment | quote }}
  RABBITMQ_PORT: {{ default "5672" .Values.slack.rabbitmqPort | quote }}
  RABBITMQ_HOST: {{ default "rabbitmq-ror.nhn-ror.svc" .Values.slack.rabbitmqHost | quote }}
  VAULT_URL: {{ default "http://ror-vault-active.nhn-ror.svc:8200" .Values.slack.vaultUrl | quote }}
  VAULT_TOKEN_TTL: {{ default "24h" .Values.slack.vaultTokenTtl | quote }}
  OPENTELEMETRY_COLLECTOR_ENDPOINT: {{ default "ror-opentelemetry-collector.nhn-ror.svc:4317" .Values.slack.otelCollectorEndpoint | quote }}
  ENABLE_TRACING: "true"
  ROLE: {{ default "ror-ms-slack" .Values.slack.role | quote }}
  ROR_URL: "https://api.ror.sky.test.nhn.no"
