---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ include "ror-cluster-agent.fullname" . }}:secret-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]