package rortypes

import (
	"github.com/NorskHelsenett/ror/pkg/config/globalconfig"
	"time"
)

// K8s PolicyReport struct generated by kyverno
type ResourcePolicyReport struct {
	Results      []ResourcePolicyReportResults `json:"results"`
	Summary      ResourcePolicyReportSummary   `json:"summary"`
	LastReported string                        `json:"lastReported,omitempty"`
}

type ResourcePolicyReportResults struct {
	Policy     string                                 `json:"policy"`
	Message    string                                 `json:"message"`
	Category   string                                 `json:"category"`
	Properties map[string]string                      `json:"properties"`
	Severity   string                                 `json:"severity"`
	Result     string                                 `json:"result"`
	Resources  []ResourcePolicyReportResultsResources `json:"resources"`
}

type ResourcePolicyReportResultsResources struct {
	Uid        string `json:"uid"`
	ApiVersion string `json:"apiVersion"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
}
type ResourcePolicyReportSummary struct {
	Error int `json:"error"`
	Fail  int `json:"fail"`
	Pass  int `json:"pass"`
	Skip  int `json:"skip"`
	Warn  int `json:"warn"`
}

// (r *ResourcePolicyReport) ApplyInputFilter Applies the input filter to the resource
func (r *ResourcePolicyReport) ApplyInputFilter(cr *CommonResource) error {
	if globalconfig.InternalNamespaces[cr.Metadata.Namespace] {
		cr.RorMeta.Internal = true
	}

	cr.RorMeta.LastReported = time.Now().Local().String()

	return nil
}

// (r ResourcePolicyReport) Get returns a pointer to the resource of type ResourcePolicyReport
func (r *ResourcePolicyReport) Get() *ResourcePolicyReport {
	return r
}
