package rortypes

import (
	"github.com/NorskHelsenett/ror/pkg/config/globalconfig"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// ResourceService K8s PolicyReport struct generated by kyverno
type ResourceService struct {
	Spec ResourceServiceSpec `json:"spec"`
}

type ResourceServiceSpec struct {
	Type                  string                 `json:"type"`
	Selector              map[string]string      `json:"selector"`
	Ports                 []ResourceServicePorts `json:"ports"`
	ClusterIP             string                 `json:"clusterIP"`
	ClusterIPs            []string               `json:"clusterIPs"`
	ExternalIPs           []string               `json:"externalIPs,omitempty"`
	ExternalName          string                 `json:"externalName,omitempty"`
	IpFamilies            []string               `json:"ipFamilies"`
	IpFamilyPolicy        string                 `json:"ipFamilyPolicy"`
	InternalTrafficPolicy string                 `json:"internalTrafficPolicy"`
	ExternalTrafficPolicy string                 `json:"externalTrafficPolicy"`
}

type ResourceServicePorts struct {
	AppProtocol string             `json:"appProtocol"`
	Name        string             `json:"name"`
	Port        int                `json:"port"`
	Protocol    string             `json:"protocol"`
	TargetPort  intstr.IntOrString `json:"targetPort"`
}

// (r *ResourceService) ApplyInputFilter Applies the input filter to the resource
func (r *ResourceService) ApplyInputFilter(cr *CommonResource) error {
	if globalconfig.InternalNamespaces[cr.Metadata.Namespace] {
		cr.RorMeta.Internal = true
	}
	return nil
}
