{
 "title": "ROR-api",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(sum(rate(container_cpu_usage_seconds_total{namespace=\"nhn-ror\"}[1m])) / sum(kube_node_status_capacity{unit=\"core\",node!~\".*control-plane.*\"})) *100\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{}[1m])) / sum(kube_node_status_capacity{unit=\"core\",node!~\".*control-plane.*\"})) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "\n(sum(container_memory_usage_bytes{namespace=\"nhn-ror\"}) / sum(kube_node_status_capacity{unit=\"byte\",node!~\".*control-plane.*\",resource=\"memory\"})) *100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(container_memory_usage_bytes) / sum(kube_node_status_capacity{unit=\"byte\",node!~\".*control-plane.*\",resource=\"memory\"})) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by status code",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_request_duration_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% error status codes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_request_duration_count{status=~\"4..\"}[$__range])) / sum(increase(http_request_duration_count{}[$__range]))) *100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(increase(http_request_duration_count{status=~\"[5-9]..\"}[$__range]))/ sum(increase(http_request_duration_count{}[$__range]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=\"nhn-ror\",deployment=~\"nhn.*\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG response time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_sum{}[5m]))  / (sum(rate(http_request_duration_count{}[5m])))) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_count{}[$__rate_interval])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most visited routes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(http_request_duration_count) by (path,method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_count{}[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most visited routes last 10 mins",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_count{}[10m])) by (path,method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of errors per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_count{status!~\"2..|3..\"}[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request duration per route in ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_sum{}[$__rate_interval])) by (path)) / (sum(rate(http_request_duration_count{}[$__rate_interval])) by (path)) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}