apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ror-api.fullname" . }}
  labels:
    {{- include "ror-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "ror-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ror-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ror-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: ror-api-cm-env
          volumeMounts:
            - name: ldap-certs-volume
              mountPath: /ldap-certs/cloud.nhn.no.pem
              subPath: cloud.nhn.no.pem
            - name: ldap-certs-volume
              mountPath: /ldap-certs/drift.nhn.no.pem
              subPath: drift.nhn.no.pem
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 9999
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 9999
          readinessProbe:
            httpGet:
              path: /health
              port: 9999
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: ldap-certs-volume
          configMap:
            name: ldap-certificates
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
